locale: 'pt'

backend:
  name: git-gateway
  branch: master

display_url: https://fecmt.com.br/
logo_url: https://fecmt.com.br/static/logo-alt-d97504e3ed884db430289875b6ed81c9.png

media_folder: static/assets
public_folder: /assets

collections:
  - name: blog
    label: Blog
    folder: _data/blog
    slug: '{{day}}-{{month}}-{{year}}-{{slug}}'
    create: true
    editor:
      preview: false
    fields:
      - {
          label: Template,
          name: template,
          widget: hidden,
          default: BlogPost,
        }
      - { name: date, label: Data, widget: datetime, dateFormat: "YYYY-MM-DD" }
      - { name: title, label: Título, widget: string }
      - { name: img, label: Imagem, widget: image, required: false }
      - { name: body, label: Body, widget: markdown }
      - { name: fonte, label: Fonte, widget: string }
  - name: convencoes
    label: Convencoes
    folder: _data/convencoes
    slug: '{{day}}-{{month}}-{{year}}-{{slug}}'
    create: true
    editor:
      preview: false
    fields:
      - {
          label: Template,
          name: template,
          widget: hidden,
          default: ConvencoesPost,
        }
      - { name: date, label: Data, widget: datetime, dateFormat: "YYYY-MM-DD" }
      - { name: name, label: Nome, widget: string }
      - { name: arquivo, label: Arquivo, widget: file }
