backend:
  name: git-gateway
  branch: master

display_url: https://fecmt.com.br/

media_folder: static/assets
public_folder: /assets

collections:
  - name: blog
    label: Blog
    folder: _data/blog
    slug: '{{day}}-{{month}}-{{year}}-{{slug}}'
    create: true
    editor:
      preview: false
    fields:
      - {
          label: Template,
          name: template,
          widget: hidden,
          default: BlogPost,
        }
      - { name: date, label: Data, widget: datetime, dateFormat: "DD.MM.YYYY" }
      - { name: title, label: Título, widget: string }
      - { name: img, label: Imagem, widget: image, required: false }
      - { name: body, label: Body, widget: markdown }
      - { name: fonte, label: Fonte, widget: string }
